// Offline generator for the short-stack open-jam chart used by decision.ts.
// Running the CFR push/fold solver live (~1-4s per stack depth) is far too slow
// for the interactive UI, so we precompute the jam SET (classes that jam at
// frequency >= 0.5) for each integer effective stack from 2..25 BB and bake it
// into a static TS module. Run with:  npx tsx src/engine/scripts/gen-pushfold-chart.ts
import { writeFileSync } from "node:fs";
import { solvePushFold } from "../gto/pushfold.js";
import { mulberry32 } from "../rng.js";

const MIN_BB = 2;
const MAX_BB = 25;
const ITERS = 200_000; // high accuracy — this is offline, run once
const JAM_THRESHOLD = 0.5;

const lines: string[] = [];
for (let bb = MIN_BB; bb <= MAX_BB; bb++) {
  const res = solvePushFold(bb, ITERS, mulberry32(0x9111 + bb));
  const jamSet = [...res.jam.entries()]
    .filter(([, f]) => f >= JAM_THRESHOLD)
    .map(([k]) => k)
    .sort();
  lines.push(`  ${bb}: ${JSON.stringify(jamSet)},`);
  // eslint-disable-next-line no-console
  console.log(`bb=${bb}: ${jamSet.length} classes jam`);
}

const out = `// AUTO-GENERATED by src/engine/scripts/gen-pushfold-chart.ts — do not edit by hand.
// Heads-up Nash short-stack open-jam ranges: for each integer effective stack
// (big blinds), the set of 169 hand-classes that jam at frequency >= ${JAM_THRESHOLD}.
// Regenerate with: npx tsx src/engine/scripts/gen-pushfold-chart.ts

const JAM_BY_BB: Record<number, string[]> = {
${lines.join("\n")}
};

const SETS = new Map<number, Set<string>>(
  Object.entries(JAM_BY_BB).map(([bb, ks]) => [Number(bb), new Set(ks)]),
);

const MIN_BB = ${MIN_BB};
const MAX_BB = ${MAX_BB};

// Does this hand-class open-jam at the given effective stack depth (BB)?
// Stacks at/above MAX_BB are out of jam-or-fold territory (caller decides);
// below MIN_BB everything jams.
export function classJams(classKey: string, stackBB: number): boolean {
  if (stackBB < MIN_BB) return true;
  const bb = Math.max(MIN_BB, Math.min(MAX_BB, Math.round(stackBB)));
  return SETS.get(bb)?.has(classKey) ?? false;
}
`;

const target = new URL("../gto/pushfold-chart.ts", import.meta.url);
writeFileSync(target, out);
// eslint-disable-next-line no-console
console.log(`\nWrote ${target.pathname}`);
